name: Build and push the server up to the hosting

on:
  workflow_dispatch:
    # Enables a button to manually run this against the main branch
    branches: [ main ]
  push:
    # Enables automatic deploys off pushes/merges into the main branch
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: ls -lsa
      
    - name: Deploy Mods
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: Evbekistan/.minecraft/
